### ISSUE TITLE
Fix Sorting order(descending) on piechart

### ISSUE THREAD

**Issue by ashrith-UMB** [UMB-CS682-Team-02/tracker#26]

**Comment by rouilj** [comment]
Ashrith, when writing up these tasks, assume that you will not be the one assigned to it.
Pretend you are leaving a note for Professor Fletcher to solve the issue.

So a description like:

Currently a pie chart always sorts the pie slices from largest (starting at 12 o'clock) to smallest.
This happens when the group is sorted in either ascending or descending order. Change this so
that sorting in descending order causes the pie chart to start with the smallest pie wedge as the
first wedge (starting at 12 o'clock and moving clockwise) and the largest pie wedge ends at 12:00.

is appropriate.

**Comment by ashrith-UMB** [comment]
Piechart can now be displayed in either way(Ascending or descending) now.

commit : https://github.com/UMB-CS682-Team-02/tracker/commit/f1fbe45918ef99331968d8be8b8da65c3b67c79d
